version: '3.4'

services:
  mywebapp:
    image: ${DOCKER_REGISTRY-}mywebapp
    build:
      context: .
      dockerfile: MyWebApp/Dockerfile
  mssql:
    image: chriseaton/adventureworks:oltp
    environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=myPassword123$
    ports:
    - "1433:1433"
  cb:
    image: couchbase:enterprise-7.0.0
    ports:
    - "8091:8091"