apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebservicedeployment
spec:
  selector:
    matchLabels:
      app: mywebservice
  replicas: 3
  template:
    metadata:
      labels:
        app: mywebservice
    spec:
      containers:
      - image: "nginxdemos/hello"
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        imagePullPolicy: Always
        name: mywebservice
        ports:
          - containerPort: 80
